# Generated by Django 3.2.12 on 2022-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.URLField(default='https://res.cloudinary.com/dro7pyxba/image/upload/v1646237011/restaurant_api/dummy_amippk.jpg'),
        ),
    ]
